language: python

python:
  - "3.7"
#  - "nightly"  # nightly build

# command to specify linux distro build should run on
dist: bionic

# command to setting framework environment variables
env:
  - DJANGO_VERSION=1.10.5

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
#  - python setup.py -q install

# command to run tests
script:
  - python manage.py test