language: python

python:
  - "3.7"
  - "nightly"  # nightly build
env:
  - DJANGO_VERSION=1.10.5
virtualenv:
  system_site_packages: true
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
# command to run tests
script:
  - python manage.py test