# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-05-17 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subweddit',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subweddit',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
