# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-05-10 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red1', '0002_auto_20200510_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='red1.LoggedInUser'),
        ),
    ]
