# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-05-11 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red1', '0003_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='weddits',
            field=models.ManyToManyField(related_name='weddits', to='red1.Subweddit'),
        ),
    ]
