# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-05-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red1', '0004_auto_20200519_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='red1.Subweddit'),
        ),
    ]
