# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-05-19 19:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('red1', '0005_auto_20200519_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='target',
            field=models.ManyToManyField(related_name='followers', to='red1.Subweddit'),
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='target',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user',
        ),
    ]
