# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-05-23 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red1', '0008_auto_20200522_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='subweddit',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subweddit',
            name='name',
            field=models.CharField(choices=[('w/tech', 'w/tech'), ('w/cars', 'w/cars'), ('w/memes', 'w/memes'), ('w/movies', 'w/movies'), ('w.facts', 'w/facts')], max_length=20),
        ),
    ]
